quarkus.http.port=8083

# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=any

# Dev Services - Disabled because using Docker Compose Keycloak
quarkus.devservices.enabled=false

# MongoDB Configuration
quarkus.mongodb.connection-string=mongodb://mongouser:mongopass@localhost:27017/notifications?authSource=admin
quarkus.mongodb.database=notifications

# Kafka Configuration
kafka.bootstrap.servers=localhost:9092

# Incoming channel for order events
mp.messaging.incoming.order-events.connector=smallrye-kafka
mp.messaging.incoming.order-events.topic=order-events
mp.messaging.incoming.order-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.order-events.auto.offset.reset=earliest
mp.messaging.incoming.order-events.enable.auto.commit=true
mp.messaging.incoming.order-events.group.id=notification-service

# Production
%prod.quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
%prod.quarkus.oidc.client-id=backend-service



