quarkus.http.port=8084
quarkus.grpc.server.port=9004
quarkus.grpc.clients."drone-service".host=localhost
quarkus.grpc.clients."drone-service".port=9002
quarkus.grpc.clients."drone-service".plain-text=true 
quarkus.rest-client."notification-service-api".url=http://localhost:8083
quarkus.rest-client."order-service-api".url=http://localhost:8082

# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=any

# Dev Services - Disabled because using Docker Compose Keycloak
quarkus.keycloak.devservices.enabled=false
quarkus.devservices.enabled=false

# Production
%prod.quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
%prod.quarkus.oidc.client-id=backend-service
%prod.quarkus.keycloak.devservices.enabled=false

