quarkus.http.port=8082
quarkus.grpc.server.port=9004
quarkus.grpc.clients."drone-service".host=localhost
quarkus.grpc.clients."drone-service".port=9002
quarkus.grpc.clients."drone-service".plain-text=true 
quarkus.rest-client."notification-service-api".url=http://localhost:8083
quarkus.rest-client."order-service-api".url=http://localhost:8080