quarkus.http.port=8081
quarkus.grpc.server.port=9002

# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=any

# Dev Services
quarkus.keycloak.devservices.enabled=true

# Production
%prod.quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
%prod.quarkus.oidc.client-id=backend-service
%prod.quarkus.keycloak.devservices.enabled=false

