quarkus.http.port=8082
quarkus.grpc.server.port=9001

# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=any

# Dev Services - Disabled because using Docker Compose Keycloak
quarkus.devservices.enabled=false

# Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=droneuser
quarkus.datasource.password=dronepass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/dronedelivery?options=-c%20timezone=UTC

# Hibernate ORM
quarkus.hibernate-orm.database.default-schema=public
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.hibernate-orm.implicit-naming-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

# Kafka Configuration
kafka.bootstrap.servers=localhost:9092

# Outgoing channel for order events
mp.messaging.outgoing.order-events.connector=smallrye-kafka
mp.messaging.outgoing.order-events.topic=order-events
mp.messaging.outgoing.order-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Production
%prod.quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
%prod.quarkus.oidc.client-id=backend-service
%prod.quarkus.keycloak.devservices.enabled=false
%prod.quarkus.hibernate-orm.database.generation=update


